# Generated by Django 4.1.6 on 2023-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.CharField(default='empty', max_length=40)),
            ],
        ),
    ]
