# Generated by Django 4.1.6 on 2023-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='user',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
