# Generated by Django 4.1.6 on 2023-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('movie', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Cеанси',
                'ordering': ['time'],
            },
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['id'], 'verbose_name': 'Зал', 'verbose_name_plural': 'Зал'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='user',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
