# Generated by Django 4.1.6 on 2023-02-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_session_alter_hall_options_alter_hall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='session',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='home.session'),
        ),
    ]
