# Generated by Django 4.1.6 on 2023-02-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-id'], 'verbose_name': 'Зал', 'verbose_name_plural': 'Зал'},
        ),
    ]
