# Generated by Django 4.1.6 on 2023-02-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='session',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='user',
        ),
    ]
